<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <SassCompilerIncludeRuntime>true</SassCompilerIncludeRuntime>
  </PropertyGroup>
  
  <!-- Only needed because we're using a ProjectReference, this is done implicitly for PackageReference's -->
  <Import Project="..\AspNetCore.SassCompiler\build\AspNetCore.SassCompiler.props" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <SassCompilerTasksAssembly Condition=" '$(Configuration)' != '' ">$(MSBuildThisFileDirectory)..\AspNetCore.SassCompiler.Tasks\bin\$(Configuration)\netstandard2.0\AspNetCore.SassCompiler.Tasks.dll</SassCompilerTasksAssembly>
    <SassCompilerTasksAssembly Condition=" '$(Configuration)' == '' ">$(MSBuildThisFileDirectory)..\AspNetCore.SassCompiler.Tasks\bin\Debug\netstandard2.0\AspNetCore.SassCompiler.Tasks.dll</SassCompilerTasksAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetCore.SassCompiler\AspNetCore.SassCompiler.csproj" />
  </ItemGroup>

  <!-- Only needed because we're using a ProjectReference, this is done implicitly for PackageReference's -->
  <Import Project="..\AspNetCore.SassCompiler\build\AspNetCore.SassCompiler.targets" />

</Project>
